name: React Native CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Build Web App
      run: npm run web:build
      env:
        CI: true

    - name: Upload Web Build
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: web-build/

    - name: Build Android App
      run: |
        cd android
        ./gradlew assembleDebug
      env:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

    - name: Upload Android Build
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk

  ios-build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install iOS dependencies
      run: |
        cd ios
        pod install

    - name: Build iOS App
      run: |
        cd ios
        xcodebuild -workspace FitTrack.xcworkspace -scheme FitTrack -configuration Debug -sdk iphonesimulator -quiet

    - name: Upload iOS Build
      uses: actions/upload-artifact@v3
      with:
        name: ios-build
        path: ios/build/